Milestone: connect API
Roseokpe/bookstore pull request #4
Opened 2022-08-19 10:34 UTC by Roseokpe

In this milestone, I connected the React-Redux application to an existing API to create and remove books in a remote server.

2022-08-19 11:00 UTC, EricMbouwe requested changes
Hi @Roseokpe, 

Good job so far 🔥!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🔥🎉
- API connection ✔
- Create and delete book ✔
- Linters ✔
- PR ✔

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-19 11:00 UTC, EricMbouwe commented on src/redux/books/books.js
> +};
- [ ] `createAsyncThunk` should be used for creating thunk action creators. It is the redux way to handle asynchronous actions.

eg: 
```js
import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import axios from 'axios'; 


export const getBooks = createAsyncThunk(
  'books/getBooks',
  async () => {
    const response = await axios.get(
      'https://us-central1-bookstore-api-e63c8.cloudfunctions.net/bookstoreApi/',
    );
    return response.data;
  },
);
```

2022-08-19 11:00 UTC, EricMbouwe commented on src/redux/books/books.js
> +};
- [ ] As mentioned above `createAsyncThunk` should be used for creating thunk action creators. It is the redux way to handle asynchronous actions.

2022-08-19 11:00 UTC, EricMbouwe commented on src/redux/books/books.js
> +};
- [ ] As mentioned above `createAsyncThunk` should be used for creating thunk action creators. It is the redux way to handle asynchronous actions.

2022-08-20 11:29 UTC, topeogunleye approved these changes
### Hi @Roseokpe, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-20 11:30 UTC, merged